### ISSUE TITLE
Execution failed for task ':qr_code_scanner:compileReleaseKotlin'.

### ISSUE THREAD

**Issue by iOSTest321** [juliuscanute/qr_code_scanner#534]
Execution failed for task ':qr_code_scanner:compileReleaseKotlin'.

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
e: /Users/prabhakar/HybridDev/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (23, 1): Class 'QRView' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /mylocation/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (216, 26): Null can not be a value of a non-null type String
e: /mylocation/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (247, 26): Null can not be a value of a non-null type String
e: /mylocation/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRView.kt: (310, 5): 'onRequestPermissionsResult' overrides nothing
e: /mylocation/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (10, 1): Class 'QRViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /mylocation/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.7.0/android/src/main/kotlin/net/touchcapture/qr/flutterqr/QRViewFactory.kt: (13, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileReleaseKotlin'.

**Flutter information**
• **Flutter version 3.0.0** at /mylocation/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
**Device (please complete the following information):**

**Screenshots**

**Additional context**
 i tried below work around
(https://github.com/juliuscanute/qr_code_scanner/issues/325#issuecomment-852171803)

https://stackoverflow.com/questions/71709605/after-successfully-a-barcode-qrcode-scanner-on-flutter-vscode-when-i-try-to-m

**Comment by nicks258** [comment]
Facing same issue after flutter update to 3.0.0.  Please help.

**Comment by RUSSCITY** [comment]
Same issue here after flutter upgrade.

**Comment by rednikisfun** [comment]
Facing the same issue after upgrading flutter to 3.0

**Comment by M123-dev** [comment]
+1

**Comment by M123-dev** [comment]
By @aaassseee in #532
> Pull request #512 already cover Flutter 3 breaking changes you can wait for @juliuscanute to merge the pull request or directly import the library by
> 
> ```yaml
>   qr_code_scanner:
>     git:
>       url: https://github.com/xeinebiu/qr_code_scanner.git
>       ref: fix_break_changes_platform
> ```

**Comment by rednikisfun** [comment]
@iOSTest321 How does one merge your code into the project?
