### ISSUE TITLE
[BUG]  execution failed for task ':qr_code_scanner:compileDebugKotlin'

### ISSUE THREAD

**Issue by marciovalim** [juliuscanute/qr_code_scanner#334]
**Describe the bug**
Code not compiling on version 0.5.1

**Flutter information**
flutter doctor -v                                              
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-arm, locale en-BR)
    • Flutter version 2.2.1 at /Users/marciovalim/Tools/flutter
    • Framework revision 02c026b03c (12 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
    • Pub download mirror https://pub.dartlang.org

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/marciovalim/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • Redmi Note 6 Pro (mobile) • 4e7b69fd • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome   • web-javascript • Google Chrome 91.0.4472.77
    ! Error: iPhone de Márcio is not connected. Xcode will continue when iPhone de Márcio is connected. (code -13)

• No issues found!

**Device (please complete the following information):**
 - Device: Redmi Note 6 Pro
 - OS: Android

** Logs **
: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/366fd3501262764ae12de7f4387f09f9/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/3c8df4d82b56271fa36b5929604ea97f/jetified-kotlin-stdlib-jdk7-1.5.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (17, 10): Class 'kotlin.jvm.JvmStatic' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/jvm/JvmStatic.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (19, 31): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (24, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (25, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class

e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (30, 9): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (39, 20): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (47, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (48, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/marciovalim/.gradle/caches/transforms-2/files-2.1/026417fda4649b36d5c39602a0c106a6/jetified-kotlin-stdlib-1.5.10.jar!/kotlin/Unit.class
e: /Users/marciovalim/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/qr_code_scanner-0.5.1/android/src/main/kotlin/net/touchcapture/qr/flutterqr/FlutterQrPlugin.kt: (52, 16): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by edsulaiman** [comment]
This is the solution [#325](https://github.com/juliuscanute/qr_code_scanner/issues/325#issuecomment-852171803)

**Comment by Justin-roy** [comment]
> This is the solution [#325](https://github.com/juliuscanute/qr_code_scanner/issues/325#issuecomment-852171803) Or you can check this commit [imp: updated gradle dependencies](https://github.com/juliuscanute/qr_code_scanner/commit/7422f73754685ea7fe854d1584c0742d43725cd8)

Same Error Getting In 2022 May

Error:
What went wrong:
Execution failed for task ':qr_code_scanner:compileDebugKotlin'.

**Comment by haashem** [comment]
Use alternative [mobile_scanner](https://pub.dev/packages/mobile_scanner). this library doesn't work in Flutter 3.0.

**Comment by Bowendev88** [comment]
please reopen this issue

**Comment by okanulkr** [comment]
You need to upgrade library to **1.0.0** and flutter to **3.0.1** and it builds. No need to change whole library, just upgrade both **qr_code_scanner** and **flutter**.

**Comment by ajiekurniawansaputra** [comment]
> You need to upgrade library to **1.0.0** and flutter to **3.0.1** and it builds. No need to change whole library, just upgrade both **qr_code_scanner** and **flutter**.

mann thank you soo so much

**Comment by misbachulmunir** [comment]
> This is the solution [#325](https://github.com/juliuscanute/qr_code_scanner/issues/325#issuecomment-852171803) Or you can check this commit [imp: updated gradle dependencies](https://github.com/juliuscanute/qr_code_scanner/commit/7422f73754685ea7fe854d1584c0742d43725cd8)
add this
dependency_overrides:
  qr_code_scanner:
    git:
      url: https://github.com/X-SLAYER/qr_code_scanner.git
      ref: flutter-beta

**Comment by 20047081-Regan** [comment]
How do i do so?

**Comment by misbachulmunir** [comment]
Like this

![Screenshot from 2022-07-11 10-08-54](https://user-images.githubusercontent.com/50521272/178181523-962ca790-cf65-48ac-bd20-0cff6d1b9690.png)

**Comment by Dani3le7** [comment]
> How do i do so?

![image](https://user-images.githubusercontent.com/79852541/182579544-55dc88bb-7675-409e-99fa-5adba70b5a52.png)

Update the lib version into your pubspec.yaml

**Comment by thejquest** [comment]
I'm using   qr_code_scanner: 1.0.1
Also, I'm using higher values than mentioned in solution https://github.com/juliuscanute/qr_code_scanner/issues/325#issuecomment-852171803
however still same issue is present. 
Additonally, I have tried updating to the version mentioned in the solution, still did not work.
This issues all started after updating the Flutter Version
