### ISSUE TITLE
[BUG] Crashed on Android devices < 7.0 (API 24)

### ISSUE THREAD

**Issue by tRuNKator** [juliuscanute/qr_code_scanner#418]
**Describe the bug**
After #369 crashed with
```
E/AndroidRuntime(24433): java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(24433): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)

```
related to https://github.com/zxing/zxing/issues/1170

**Flutter information**
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1110], locale ru-RU)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (8 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\tRuNKator\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

**Device (please complete the following information):**
 - Device: Android < 7.0 (API 24)

**Comment by racifuina** [comment]
I downgraded to 0.4.0 to make it work on Android 6.0

**Comment by tRuNKator** [comment]
> I downgraded to 0.4.0 to make it work on Android 6.0

You can simply enable desugaring in android module.
https://developer.android.com/studio/write/java8-support

**Comment by v360-bruno-sato** [comment]
I'm having the same issue.
`Fatal Exception: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)`
@tRuNKator do you find the solution?

**Comment by sondo65** [comment]
Hi @ViniciusSossela , which version will support old sdk ? Thanks

**Comment by juliansteenbakker** [comment]
This is implemented in version 0.6.0. Please try again and comment if problem still exists.
