### ISSUE TITLE
[BUG] Undefined symbol: _OBJC_CLASS_$_FlutterQrPlugin when build ios

### ISSUE THREAD

**Issue by weishirongzhen** [juliuscanute/qr_code_scanner#365]
**Describe the bug**
build error
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale zh-Hans-CN)
    • Flutter version 2.2.3 at /Users/wei/flutter
    • Framework revision f4abaa0735 (12 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

**Screenshots**

**Additional context**
    ld: warning: ignoring file /Users/wei/project/refuse/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning, missing required
    architecture armv7 in file /Users/wei/project/refuse/ios/Pods/MLKitBarcodeScanning/Frameworks/MLKitBarcodeScanning.framework/MLKitBarcodeScanning (2 slices)
    ld: warning: ignoring file /Users/wei/project/refuse/ios/Pods/MLKitVision/Frameworks/MLKitVision.framework/MLKitVision, missing required architecture armv7 in file
    /Users/wei/project/refuse/ios/Pods/MLKitVision/Frameworks/MLKitVision.framework/MLKitVision (2 slices)
    ld: warning: ignoring file /Users/wei/project/refuse/build/ios/Release-iphoneos/qr_code_scanner/qr_code_scanner.framework/qr_code_scanner, building for iOS-armv7 but
    attempting to link with file built for iOS-arm64
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_FlutterQrPlugin", referenced from:
          objc-class-ref in GeneratedPluginRegistrant.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by juliansteenbakker** [comment]
Can you try this: https://stackoverflow.com/a/63868625

**Comment by weishirongzhen** [comment]
> Can you try this: https://stackoverflow.com/a/63868625

Still can't build success, This only happen on 1.0.0-alpha.1 btw.
works well on 0.5.2

**Comment by weishirongzhen** [comment]
> Which device are you using? 1.0.0-alpha.1 only supports iOS 10 > and only 64 bit devices.

I'm using iphone 12 physical device with ios14.6

**Comment by juliansteenbakker** [comment]
No i think iOS 10 will also work. However i think we need to remove the 32 bit capability from info.plist like done here: https://github.com/FirebaseExtended/mlkit-material-ios/issues/4#issuecomment-495817937

**Comment by weishirongzhen** [comment]
> No i think iOS 10 will also work. However i think we need to remove the 32 bit capability from info.plist like done here: [FirebaseExtended/mlkit-material-ios#4 (comment)](https://github.com/FirebaseExtended/mlkit-material-ios/issues/4#issuecomment-495817937)

Thanks ,it worked.

**Comment by Nolat** [comment]
@weishirongzhen How did you remove the 32 bit capability with XCode 12?
